name: null
favicon: null
layout_spectrum: 0.49739159969612956
typography_spectrum: 0.7130953792948276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8440926617477089
  lightness: 0.8691101097501814
  saturation: 0.4796437176410109
  rhythmicContrast: 0.05338984658010304
purpose: []
